### ISSUE TITLE
Moving Sidebar to the left

### ISSUE THREAD

**Issue by ishu3101** [mvarela/orbit-cv#2]
How do you move the sidebar from the right side to the left side? Would love to be able to have an option as to which side you would like to have the sidebar?

**Comment by mvarela** [comment]
At the moment there's no simple way of doing that. I hadn't planned on it, since this was meant to be just a port of Orbit, but I'll have a look.

**Comment by mvarela** [comment]
I've added a leftSidebar option to the class. When you pass it, the sidebar will be rendered on the left side of the page.

**Comment by ishu3101** [comment]
Great. I would recommend adding an example of how to display sidebar on the left in the README.md
plus include one or more images showing the left sidebar with the different color schemes as demo.
