### ISSUE TITLE
Education section is not spaced in Orbit-CV like in Hugo-Orbit

### ISSUE THREAD

**Issue by dnk8n** [mvarela/orbit-cv#5]
E.g.

Hugo-Orbit (desired format)
![Screenshot from 2019-12-09 18-51-05](https://user-images.githubusercontent.com/3307753/70455514-1e6bb780-1ab5-11ea-83ae-df8b071a55df.png)

Orbit-CV
![Screenshot from 2019-12-09 18-48-16](https://user-images.githubusercontent.com/3307753/70455538-262b5c00-1ab5-11ea-9e35-7cfc246c163d.png)

One would desire the date to follow on its own line, not directly after the University.

**Comment by dnk8n** [comment]
Great stuff. Fix confirmed to be working. Appreciated

**Comment by mvarela** [comment]
Glad to hear!
